name: safe_bloc
description: App BLoC base classes with support of unexpected error
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  bloc: ^8.1.1
  bloc_presentation: ^0.2.1+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  meta: ^1.8.0
  uuid: ^3.0.7

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  netglade_analysis: ^4.0.0
