name: safe_bloc
description: An extension to bloc state management library that manages unexpected exceptions.
version: 1.1.0
repository: https://github.com/netglade/safe_bloc
issue_tracker: https://github.com/netglade/safe_bloc/issues
screenshots:
  - description: The safe_bloc package logo.
    path: doc/icon.png

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  bloc_presentation: ^1.0.0
  bloc_test: ^9.1.5
  diff_match_patch: ^0.4.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  meta: ^1.8.0
  test: ^1.24.3
  uuid: ^4.1.0

dev_dependencies:
  netglade_analysis: ^6.0.0
