name: safe_bloc
description: An extension to bloc state management library that manages unexpected exceptions.
version: 1.4.0
repository: https://github.com/netglade/safe_bloc
issue_tracker: https://github.com/netglade/safe_bloc/issues
screenshots:
  - description: The safe_bloc package logo.
    path: doc/icon.png

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  bloc: ^9.0.0
  bloc_presentation: ^1.1.0
  bloc_test: ^10.0.0
  diff_match_patch: ^0.4.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  meta: ^1.15.0
  test: ^1.25.8
  trackable: ^1.0.2
  uuid: ^4.5.1

dev_dependencies:
  netglade_analysis: ^15.0.0
