name: safe_bloc
description: App BLoC base classes with support of unexpected error
version: 1.0.0
repository: https://github.com/netglade/safe_bloc
issue_tracker: https://github.com/netglade/safe_bloc/issues

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  bloc: ^8.1.1
  bloc_presentation: ^0.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  meta: ^1.8.0
  uuid: ^4.0.0

dev_dependencies:
  netglade_analysis: ^4.2.0
