name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.8.0

      - name: Install Dependencies
        run: flutter pub get

      - name: Format
        run: dart format --line-length 120 .

      - name: Flutter Analyze
        run: dart analyze .

      - name: Install DCM
        uses: CQLabs/setup-dcm@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run DCM
        uses: CQLabs/dcm-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ci-key: ${{ secrets.DCM_KEY }}
          email: ${{ secrets.DCM_EMAIL }}
          folders: .
          fatal-found: true

      - name: Dry Publish
        run: dart pub publish --dry-run